### ISSUE TITLE
env MODS not working

### ISSUE THREAD

**Issue by liyechen** [yeet-zone/docker-dontstarvetogether#149] opened 2021-04-14 03:39 UTC
Hi, I write my `.env` file like this:
```yaml
# ... some configs
MODS=378160973,375859599,356930882,1271089343,501385076,2110246021,466732225
# ... some configs
```
And I run the container, but in the container's `/data/mods/dedicated_server_mods_setup.lua`, there is no `ServerModSetup(xxx)` but a default file with some comments like:
```lua
--There are two functions that will install mods, ServerModSetup and ServerModCollectionSetup. Put the calls to the functions in this file and they will be executed on boot.

--ServerModSetup takes a string of a specific mod's Workshop id. It will download and install the mod to your mod directory on boot.
	--The Workshop id can be found at the end of the url to the mod's Workshop page.
	--Example: http://steamcommunity.com/sharedfiles/filedetails/?id=350811795
	--ServerModSetup("350811795")

--ServerModCollectionSetup takes a string of a specific mod's Workshop id. It will download all the mods in the collection and install them to the mod directory on boot.
	--The Workshop id can be found at the end of the url to the collection's Workshop page.
	--Example: http://steamcommunity.com/sharedfiles/filedetails/?id=379114180
	--ServerModCollectionSetup("379114180")

```

**Comment by thasmo** [comment] 2021-04-14 14:08
@liyechen, I'll have a look at it as soon as possible. Thanks for bringing this up!

**Comment by liyechen** [comment] 2021-04-15 01:36
> @liyechen, I'll have a look at it as soon as possible. Thanks for bringing this up!

Sure and thanks for that!  I don't know if I'm the special case maybe it's my problem! Anyway thanks for that again!

**Comment by thasmo** [comment] 2021-04-16 17:31
@liyechen, I've checked mod setup using the documented [mods recipe](yeetzone/docker-dontstarvetogether/tree/master/docs/recipes/mods). Did you try that too? I've changed the recipe recently which may is the reason it is working now but wasn't earlier, because the data mount was read-only before.

Feel free to have a look at the `mods` recipe which seems to work for me. If it doesn't or if it doesn't work for your own setup, please let me know so we can figure this out! 😄

**Comment by liyechen** [comment] 2021-04-17 12:27
> @liyechen, I've checked mod setup using the documented [mods recipe](yeetzone/docker-dontstarvetogether/tree/master/docs/recipes/mods). Did you try that too? I've changed the recipe recently which may is the reason it is working now but wasn't earlier, because the data mount was read-only before.
> 
> Feel free to have a look at the `mods` recipe which seems to work for me. If it doesn't or if it doesn't work for your own setup, please let me know so we can figure this out! 😄

Sure and I will try it. Thanks for your time !

**Comment by thasmo** [comment] 2021-04-18 17:05
FYI; there is a current issue where mod files do not get installed correctly due to a write-permission problem.

**Comment by novikmisha** [comment] 2021-04-21 15:51
I have exactly the same issue. Trying to set up server from mods recipe (the only difference is that I add password) makes server with no mods at all - [image](https://i.imgur.com/Niy8qD8.png)

**Comment by victorperin** [comment] 2021-04-21 21:35
Same here, mods are not loading. My configuration uses STEAM_GROUP_ID, insead of password.

**Comment by thasmo** [comment] 2021-04-21 22:01
Thanks for your input on this! :+1: I'll probably have a look at this on the coming weekend.

**Comment by mateuszkozakiewicz** [comment] 2021-04-24 01:06
For me the `dedicated_server_mods_setup.lua` looks fine, however the mods themselves are missing, they should be in `/data/mods/workshop-xxxxxxx` , after manually downloading the mods and putting them in `/data/mods` everything works. Hope it helps you debug.

**Comment by thasmo** [comment] 2021-04-24 18:18
Invested some hours into this but have nothing new to report unfortunately. Running `dontstarvetogether start` within the running container seems to properly create the directories and install the mods. I don't know why this is not working on container start.

**Comment by mateuszkozakiewicz** [comment] 2021-04-25 00:48
This fixes all problems

[`/entrypoint.sh`](https://github.com/yeetzone/docker-dontstarvetogether/blob/master/build/entrypoint.sh#L18)
```
        dontstarve_dedicated_server_nullrenderer -only_update_server_mods -ugc_directory $STEAM_PATH/ugc_mods | true
```
[`/opt/steam/scripts/command/start/script.sh`](https://github.com/yeetzone/docker-dontstarvetogether/blob/master/build/scripts/command/start/script.sh#L20-L25)
```
exec dontstarve_dedicated_server_nullrenderer \
        -skip_update_server_mods \
        -ugc_directory "$STEAM_PATH/ugc_mods" \
        -persistent_storage_root "$(dirname "$STORAGE_PATH")" \
        -conf_dir "$(basename "$STORAGE_PATH")" \
        -cluster "$CLUSTER_NAME" \
        -shard "$SHARD_NAME" \
        -backup_log_count "$BACKUP_LOG_COUNT"
```
Additionally this allows to use mods uploaded to workshop using the new method (note `-ugc_directory` without it some mods crash the server on startup i.e. global positions)

I think there is a permission issue because this

> Running dontstarvetogether start within the running container seems to properly create the directories and install the mods.

is only true if you exec into container and run `dontstarve_dedicated_server_nullrenderer` as `root`, the `steam` user will never be able to install mods unless root runs that command first (some dir is created perhaps?)

**Comment by thasmo** [comment] 2021-04-25 11:21
@mateuszkozakiewicz, thanks for your help! I've now incorporated two separate changes based on your input.

First, I'm "brute-forcing" `chmod` in the `entrypoint.sh` to ensure proper permissions for the `$STEAM_PATH` directory. This was probably the issue in the first place. The solution is not super nice, but it executes fast and it seems to work anyway.

Second, I've integrated usage of the new `ugc_directory` parameter, using it slightly different than what you proposed. The actual installation/update of mods happens in the `update` script, which is called from the `start` script. Then, as you suggest, I'm using `skip_update_server_mods` on the actual launch command.

So far this seems to fix the mods issue; although I noticed that now, mods are still installed into the `mods` directory, but in addition to that, some files also get installed into the `ugc_mods` directory.

The Docker image has already been updated on the Docker hub. Please feel free to pull the new image via `docker pull yeetzone/dontstarvetogether` and give it a try. I'll leave the issue open until I get some confirmation this works.

Thanks a lot to everyone participating on this issue! ❤️

**Comment by mateuszkozakiewicz** [comment] 2021-04-25 13:55
> So far this seems to fix the mods issue; although I noticed that now, mods are still installed into the mods directory, but in addition to that, some files also get installed into the ugc_mods directory.

AFAIK this is an intended behaviour, old mods use the ./mods path and new ones use the path given in the parameter, this has something to do with recently released mod uploader tool by Klei. 
Glad you fixed the image, thanks!

**Comment by thasmo** [comment] 2021-04-26 07:44
This should be fixed.

> The Docker image has already been updated on the Docker hub. Please feel free to pull the new image via docker pull yeetzone/dontstarvetogether and give it a try.

**Closed as completed by thasmo** 2021-04-26 07:44 UTC
Labels: bug, research

**Comment by jeliasson** [comment] 2021-06-02 18:59
It seems like the mods is not working in the latest `yeetzone/dontstarvetogether:latest` build. Using below and it does not give anything in the logs.
```yaml
MODS: 378160973,345692228,351325790
```
