### ISSUE TITLE
Mods are downloaded but not enabled

### ISSUE THREAD

**Issue by dbiagi** [yeet-zone/docker-dontstarvetogether#119] opened 2017-12-27 11:22 UTC
I'm banging my head for quite some time now trying to make a modded server. But I cant make mods work. Server is listed but without mods.
The log file tells that mods is being downloaded, but for some reason, they are not enabled.
I'll paste my files here, maybe someone can help me figure it out.

docker-compose.yml:
```yml
version: "2"

services:
  world-2:
    image: dstacademy/dontstarvetogether:0.7.1
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    ports:
      - "11000:10999/udp"
    env_file:
      - "world-2.env"
    environment:
      MODS_OVERRIDES: |
        return {
        	['workshop-378160973'] = { enabled = true },
        	['workshop-492173795'] = { enabled = true },
        	['workshop-666155465'] = { enabled = true },
        	['workshop-1157975551'] = { enabled = true }
        }
    volumes:
        - "./world-2:/var/lib/dsta/cluster"
```

world-2.env:
```env
TOKEN=MY_TOKEN
NAME=dBiagi Server
MAX_PLAYERS=4
LANGUAGE=brazilian
PASSWORD=PWD
PAUSE_WHEN_EMPTY=true
ADMINLIST=KU_-YqO-h_6

#378160973 - Global Positions
#492173795 - Moderator Commands
#666155465 - Show Me
#1157975551 - Extended Map Icons
MODS=378160973,492173795,666155465,1157975551
```

server_log.txt:
```
[00:00:00]: PersistRootStorage is now /var/lib/dsta//./cluster/shard/ 
[00:00:00]: Starting Up
[00:00:00]: Version: 247691
[00:00:00]: Current time: Wed Dec 27 11:13:47 2017

[00:00:00]: System Name: Linux
[00:00:00]: Host Name: e282dd2a4ae5
[00:00:00]: Release(Kernel) Version: 4.13.0-21-generic
[00:00:00]: Kernel Build Timestamp: #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
[00:00:00]: Machine Arch: x86_64
[00:00:00]: Don't Starve Together: 247691 LINUX
[00:00:00]: Build Date: 3184
[00:00:00]: Parsing command line
[00:00:00]: Command Line Arguments: -persistent_storage_root /var/lib/dsta -conf_dir . -cluster cluster -shard shard -backup_log_count 0 
[00:00:00]: Initializing distribution platform
[00:00:00]: ....Done
[00:00:00]: Mounting file system databundles/shaders.zip successful.
[00:00:00]: Mounting file system databundles/fonts.zip successful.
[00:00:00]: Mounting file system databundles/anim_dynamic.zip successful.
[00:00:00]: Mounting file system databundles/bigportraits.zip successful.
[00:00:00]: Mounting file system databundles/images.zip successful.
[00:00:00]: THREAD - started 'GAClient' (4145331008)
[00:00:00]: Mounting file system databundles/scripts.zip successful.
[00:00:00]: CurlRequestManager::ClientThread::Main()
[00:00:00]: ProfileIndex:4.60
[00:00:00]: [Connect] PendingConnection::Reset(true)
[00:00:00]: Network tick rate: U=15(2), D=0
[00:00:00]: Network tick rate: U=15(2), D=0
[00:00:00]: Error trying to change cluster setting (NETWORK->cluster_intention) from '' to 'cooperative'
[00:00:00]: OnLoadPermissionList: /var/lib/dsta//./cluster/blocklist.txt (Failure)
[00:00:00]: OnLoadPermissionList: /var/lib/dsta//./cluster/adminlist.txt (Success)
[00:00:00]: THREAD - started 'StreamInput' (4138728256)
[00:00:00]: OnLoadUserIdList: /var/lib/dsta//./cluster/whitelist.txt (Failure)
[00:00:00]: Token retrieved from: /var/lib/dsta//./cluster/cluster_token.txt
[00:00:00]: Token retrieved from: /var/lib/dsta//./cluster/cluster_token.txt
[00:00:00]: cGame::InitializeOnMainThread
[00:00:00]: Renderer initialize: Okay
[00:00:00]: AnimManager initialize: Okay
[00:00:00]: Buffers initialize: Okay
[00:00:00]: cDontStarveGame::DoGameSpecificInitialize()
[00:00:00]: GameSpecific initialize: Okay
[00:00:00]: cGame::StartPlaying
[00:00:00]: LOADING LUA
[00:00:00]: DoLuaFile scripts/main.lua
[00:00:00]: DoLuaFile loading buffer scripts/main.lua
[00:00:00]:   taskgrouplist:	default	Together	
[00:00:00]:   taskgrouplist:	classic	Classic	
[00:00:00]:   taskgrouplist:	cave_default	Underground	
[00:00:00]:   taskgrouplist:	lavaarena_taskset	The Forge	
[00:00:00]: running main.lua
	
[00:00:00]: Could not load modindex	
[00:00:00]: ModIndex: Beginning normal load sequence for dedicated server.
	
[00:00:00]: DownloadMods(4)
[00:00:00]: Download server mod 378160973
[00:00:00]: Download server mod 492173795
[00:00:01]: Download server mod 666155465
[00:00:06]: Download server mod 1157975551
[00:00:07]: LOADING LUA SUCCESS
[00:00:07]: PlayerDeaths could not load morgue	
[00:00:07]: PlayerHistory could not load player_history	
[00:00:07]: bloom_enabled	false	
[00:00:07]: Could not load saveindex	
[00:00:07]: OnFilesLoaded()	
[00:00:07]: OnUpdatePurchaseStateComplete	
[00:00:08]: 	Load FE	
[00:00:08]: THREAD - started 'FilesExistAsyncThread' (4121680704)
[00:00:08]: FilesExistAsyncThread started (12982 files)...
[00:00:08]: 	Load FE: done	
[00:00:08]: ModIndex: Load sequence finished successfully.	
[00:00:08]: Reset() returning
[00:00:08]: ... FilesExistAsyncThread complete
[00:00:09]: [200] Account Communication Success (6)
[00:00:09]: Received (KU_-YqO-h_6) from TokenPurpose
[00:00:09]: Starting Dedicated Server Game	
[00:00:09]: Network tick rate: U=15(2), D=0
[00:00:09]: About to start a server with the following settings:
[00:00:09]:   Dedicated: true
[00:00:09]:   Online: true
[00:00:09]:   Passworded: true
[00:00:09]:   ServerPort: 10999
[00:00:09]:   SteamAuthPort: 8766
[00:00:09]:   SteamMasterServerPort: 27016
[00:00:09]:   ClanID: false
[00:00:09]:   ClanOnly: false
[00:00:09]:   ClanAdmin: false
[00:00:09]:   LanOnly: false
[00:00:09]:   FriendsOnly: false
[00:00:09]:   EnableAutosaver: true
[00:00:09]:   EncodeUserPath: false
[00:00:09]:   PVP: false
[00:00:09]:   MaxPlayers: 4
[00:00:09]:   GameMode: survival
[00:00:09]:   OverridenDNS: 
[00:00:09]:   PauseWhenEmpty: true
[00:00:09]:   IdleTimeout: 1800s
[00:00:09]:   VoteEnabled: true
[00:00:09]:   InternetBroadcasting: true
[00:00:09]:   Intent: cooperative
[00:00:09]: [Shard] Shard server mode disabled by configuration file
[00:00:09]: Online Server Started on port: 10999
[00:00:09]: Not applying level data overrides.	
[00:00:09]: Not applying world gen overrides.	
[00:00:09]: Collecting garbage...
[00:00:09]: lua_gc took 0.02 seconds
[00:00:09]: ~ShardLuaProxy()
[00:00:09]: ~ItemServerLuaProxy()
[00:00:09]: ~InventoryLuaProxy()
[00:00:09]: ~NetworkLuaProxy()
[00:00:09]: ~SimLuaProxy()
[00:00:09]: lua_close took 0.02 seconds
[00:00:09]: ReleaseAll
[00:00:09]: ReleaseAll Finished
[00:00:09]: cGame::StartPlaying
[00:00:09]: LOADING LUA
[00:00:09]: DoLuaFile scripts/main.lua
[00:00:09]: DoLuaFile loading buffer scripts/main.lua
[00:00:09]:   taskgrouplist:	default	Together	
[00:00:09]:   taskgrouplist:	classic	Classic	
[00:00:09]:   taskgrouplist:	cave_default	Underground	
[00:00:09]:   taskgrouplist:	lavaarena_taskset	The Forge	
[00:00:09]: running main.lua
	
[00:00:09]: loaded modindex	
[00:00:09]: ModIndex: Beginning normal load sequence for dedicated server.
	
[00:00:09]: LOADING LUA SUCCESS
[00:00:09]: PlayerDeaths could not load morgue	
[00:00:09]: PlayerHistory could not load player_history	
[00:00:09]: bloom_enabled	false	
[00:00:09]: OnLoad slot	2	: World options was nil! Populating with default.	
[00:00:09]: OnLoad slot	3	: World options was nil! Populating with default.	
[00:00:09]: OnLoad slot	4	: World options was nil! Populating with default.	
[00:00:09]: OnLoad slot	5	: World options was nil! Populating with default.	
[00:00:09]: loaded saveindex	
[00:00:09]: OnFilesLoaded()	
[00:00:09]: OnUpdatePurchaseStateComplete	
[00:00:09]: Load Slot: ... generating new world	
[00:00:09]: WorldSim::SimThread::SimThread()
[00:00:09]: ABOUT TO INSTALL STACKTRACE
[00:00:09]: DoLuaFile scripts/stacktrace.lua
[00:00:09]: DoLuaFile loading buffer scripts/stacktrace.lua
[00:00:09]: INSTALLED STACKTRACE
[00:00:09]: WorldSim::SimThread::SimThread() complete
[00:00:09]: THREAD - started 'WorldSim' (4063230784)
[00:00:09]: WorldSim::SimThread::Main()
[00:00:09]: DoLuaFile scripts/worldgen_main.lua
[00:00:09]: DoLuaFile loading buffer scripts/worldgen_main.lua
[00:00:09]: ModIndex: Load sequence finished successfully.	
[00:00:09]: Reset() returning
[00:00:09]: DLC enabled : 	false	
[00:00:09]:   taskgrouplist:	default	Together	
[00:00:09]:   taskgrouplist:	classic	Classic	
[00:00:09]:   taskgrouplist:	cave_default	Underground	
[00:00:09]:   taskgrouplist:	lavaarena_taskset	The Forge	
[00:00:09]: running worldgen_main.lua
	
[00:00:09]: SEED = 	1514373236	
[00:00:09]: Generating world with these parameters:	
[00:00:09]: level_type	SURVIVAL	
[00:00:09]: level_data:	
[00:00:09]: 	K: 	1	 V: 	table: 0xf174d4e0	
[00:00:09]: 		K: 	desc	 V: 	The standard Don't Starve experience.	
[00:00:09]: 		K: 	hideminimap	 V: 	false	
[00:00:09]: 		K: 	id	 V: 	SURVIVAL_TOGETHER	
[00:00:09]: 		K: 	location	 V: 	forest	
[00:00:09]: 		K: 	max_playlist_position	 V: 	999	
[00:00:09]: 		K: 	min_playlist_position	 V: 	0	
[00:00:09]: 		K: 	name	 V: 	Default	
[00:00:09]: 		K: 	numrandom_set_pieces	 V: 	4	
[00:00:09]: 		K: 	ordered_story_setpieces	 V: 	table: 0xf174d508	
[00:00:09]: 			K: 	1	 V: 	Sculptures_1	
[00:00:09]: 			K: 	2	 V: 	Maxwell5	
[00:00:09]: 		K: 	override_level_string	 V: 	false	
[00:00:09]: 		K: 	overrides	 V: 	table: 0xf1750158	
[00:00:09]: 			K: 	layout_mode	 V: 	LinkNodesByKeys	
[00:00:09]: 			K: 	roads	 V: 	default	
[00:00:09]: 			K: 	season_start	 V: 	default	
[00:00:09]: 			K: 	start_location	 V: 	default	
[00:00:09]: 			K: 	task_set	 V: 	default	
[00:00:09]: 			K: 	world_size	 V: 	default	
[00:00:09]: 			K: 	wormhole_prefab	 V: 	wormhole	
[00:00:09]: 		K: 	random_set_pieces	 V: 	table: 0xf174dff0	
[00:00:09]: 			K: 	1	 V: 	Sculptures_2	
[00:00:09]: 			K: 	2	 V: 	Sculptures_3	
[00:00:09]: 			K: 	3	 V: 	Sculptures_4	
[00:00:09]: 			K: 	4	 V: 	Sculptures_5	
[00:00:09]: 			K: 	5	 V: 	Chessy_1	
[00:00:09]: 			K: 	6	 V: 	Chessy_2	
[00:00:09]: 			K: 	7	 V: 	Chessy_3	
[00:00:09]: 			K: 	8	 V: 	Chessy_4	
[00:00:09]: 			K: 	9	 V: 	Chessy_5	
[00:00:09]: 			K: 	10	 V: 	Chessy_6	
[00:00:09]: 			K: 	11	 V: 	Maxwell1	
[00:00:09]: 			K: 	12	 V: 	Maxwell2	
[00:00:09]: 			K: 	13	 V: 	Maxwell3	
[00:00:09]: 			K: 	14	 V: 	Maxwell4	
[00:00:09]: 			K: 	15	 V: 	Maxwell6	
[00:00:09]: 			K: 	16	 V: 	Maxwell7	
[00:00:09]: 			K: 	17	 V: 	Warzone_1	
[00:00:09]: 			K: 	18	 V: 	Warzone_2	
[00:00:09]: 			K: 	19	 V: 	Warzone_3	
[00:00:09]: 		K: 	required_prefabs	 V: 	table: 0xf174d630	
[00:00:09]: 			K: 	1	 V: 	multiplayer_portal	
[00:00:09]: 		K: 	substitutes	 V: 	table: 0xf174f948	
[00:00:09]: 		K: 	version	 V: 	3	
[00:00:09]: 
#######
#
# Generating SURVIVAL Mode Level
#
#######
	
[00:00:09]: Prefab Swap Selection: regular grass	
[00:00:09]: Prefab Swap Selection: regular twigs	
[00:00:09]: Prefab Swap Selection: regular berries	
[00:00:09]: Sculptures_4	added to	Dig that rock	
[00:00:09]: Chessy_5	added to	Befriend the pigs	
[00:00:09]: Maxwell2	added to	Kill the spiders	
[00:00:09]: Maxwell7	added to	Beeeees!	
[00:00:09]: New size:	425	default	
[00:00:09]: Creating story...	
[00:00:09]: LinkNodesByKeys	
[00:00:09]: Finding valid start task...	
[00:00:09]:    ...picked 	Make a pick	
[00:00:09]: Has start node	Clearing	
[00:00:09]: Baking map...	425	
[00:00:09]: [WorldSimActual::GenerateVoronoiMap]
[00:00:09]: GenerateVoronoiMap [1]:
[00:00:09]: ...Done.
[00:00:09]: [AddEmptyNodes]
[00:00:09]: GenerateVoronoiMap [100]:
[00:00:11]: ...Done.
[00:00:11]: [WorldSimActual::GenerateVoronoiMap] complete [success]
[00:00:11]: [WorldSimActual::ConvertToTileMap]
[00:00:11]: [ConvertToTileMap]
[00:00:11]: [WorldSimActual::ConvertToTileMap] complete
[00:00:11]: [WorldSimActual::SeparateIslands]
[00:00:11]: [SeparateIslands]
[00:00:11]: [WorldSimActual::SeparateIslands] complete
[00:00:11]: Map Baked!	
[00:00:11]: [WorldSimActual::ForceConnectivity]
[00:00:11]: [GenerateLandmasses]
[00:00:11]: [MergeConnectedLandmasses] true
[00:00:11]: [WorldSimActual::ForceConnectivity] complete
[00:00:11]: [GetWormholesExtra] connected 0 unconnected 1
[00:00:11]: [GetWormholesExtra] after: connected 1 unconnected 0
[00:00:11]: [GetWormholesExtra] pushed 0 wormholes
[00:00:11]: [WorldSimActual::DrawRoads]
[00:00:11]: [DrawRoads]
[00:00:11]: [WorldSimActual::DrawRoads] complete
[00:00:11]: Encoding...	
[00:00:11]: Encoding... DONE	
[00:00:11]: Checking Tags	
[00:00:11]: Populating voronoi...	
[00:00:11]: Warning! Could not find a spot for Maxwell2 in node Kill the spiders:BG_103:BGRocky	
[00:00:11]: disconnected tiles...	0	
[00:00:12]: Checking Required Prefab multiplayer_portal has at least 1 instances (1 found).	
[00:00:12]: Checking Required Prefab pigking has at least 1 instances (1 found).	
[00:00:12]: Done forest map gen!	
[00:00:12]: Checking map...	
[00:00:12]: Generation complete	
[00:00:12]: WorldSim::SimThread::Main() complete
[00:00:12]: Serializing world: session/3434EE0D7EFA07A8/0000000002
[00:00:12]: Auto-enabling encoded user paths
[00:00:12]: 	Unload FE	
[00:00:12]: 	Unload FE done	
[00:00:12]: 	LOAD BE	
[00:00:14]: 	LOAD BE: done	
[00:00:14]: Begin Session: 3434EE0D7EFA07A8
[00:00:14]: saving to server_temp/server_save	
[00:00:14]: MiniMapComponent::AddAtlas( minimap/minimap_data.xml )
[00:00:14]: Loading Nav Grid	
[00:00:17]: Reconstructing topology	
[00:00:17]: 	...Sorting points	
[00:00:17]: 	...Sorting edges	
[00:00:17]: 	...Connecting nodes	
[00:00:17]: 	...Validating connections	
[00:00:17]: 	...Housekeeping	
[00:00:17]: 	...Done!	
[00:00:17]: 1 uploads added to server. From server_temp
[00:00:17]: Telling Client our new session identifier: 3434EE0D7EFA07A8
[00:00:17]: [Steam] SteamGameServer_Init(8766, 10999, 27016)
[00:00:17]: [Steam] SteamGameServer_Init success
[00:00:17]: Validating portal[1] <-> <nil>[1] (inactive)	
[00:00:17]: Validating portal[2] <-> <nil>[2] (inactive)	
[00:00:17]: Validating portal[3] <-> <nil>[3] (inactive)	
[00:00:17]: Validating portal[4] <-> <nil>[4] (inactive)	
[00:00:17]: Validating portal[5] <-> <nil>[5] (inactive)	
[00:00:17]: Validating portal[6] <-> <nil>[6] (inactive)	
[00:00:17]: Validating portal[7] <-> <nil>[7] (inactive)	
[00:00:17]: Validating portal[8] <-> <nil>[8] (inactive)	
[00:00:17]: Validating portal[9] <-> <nil>[9] (inactive)	
[00:00:17]: Validating portal[10] <-> <nil>[10] (inactive)	
[00:00:17]: Sim paused
```

**Comment by thasmo** [comment] 2017-12-27 11:22
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by thasmo** [comment] 2017-12-27 11:23
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

Possibly related issues are #79 (Mods are not working), and #86 (No auth token could be found.).

**Comment by thasmo** [comment] 2017-12-27 11:39
@dbiagi If you're only enabling mods and do not change other mod-settings you don't need `MODS_OVERRIDES` to be set manually; just remove it.

Did you delete the `./world-2` directory, after each try? Maybe there are old config files which prevent using new `ENV` settings. Also, you may try to load each mod alone, to be sure it's not a single mod which is troublesome.

**Comment by thasmo** [comment] 2017-12-27 11:40
Maybe @BraisGabin has some more ideas. 😄

**Comment by BraisGabin** [comment] 2017-12-27 11:57
I agree with @thasmo.

It seems that you are keeping the configuration from the first launch. This issue will be fixed in the next version. Mean while remove the volume between each try if you can, or just remove the file `/var/lib/dsta/cluster/shard/modoverrides.lua`.

**Comment by dbiagi** [comment] 2017-12-27 12:00
I already had trouble with old files messing configs some time ago, so everytime I retry, I type:

```docker-compose rm world-2```
and
```sudo rm -rf world-2/*```

But its not helping this time.

I'll try activating one mod at a time. Lets see if it helps.
Thank you for your help =)

**Comment by dbiagi** [comment] 2017-12-27 13:42
Tried the following:

One mod at a time.
Copied all files from [this folder](https://github.com/dst-academy/docker-dontstarvetogether/tree/v0.7.1/docs/examples/mods), changed only the token and the server name.
Tried on another machine.

All atempts with same results. Mods downloaded as showed in log file, server listed, but no mod active.

**Comment by thasmo** [comment] 2017-12-27 13:47
If you use the example `docker-compose.yml` file, be sure to use `image: dstacademy/dontstarvetogether:0.7` and not `image: dstacademy/dontstarvetogether`.

**Comment by BraisGabin** [comment] 2017-12-27 14:52
I think that I have an easy way to reproduce this error: 

```
docker run --rm -e TOKEN="YOUR-TOKEN" -e MODS="378160973" -p "10999:10999/udp" dstacademy/dontstarvetogether:0.7.1 --update=all
```

I'm going to check with our last version.

**Comment by BraisGabin** [comment] 2017-12-27 15:10
Ok, it seems that the mods are not dowloaded. I have no idea why right now.

**Comment by BraisGabin** [comment] 2017-12-27 15:15
Andddddd it's the Klei's fault again 🎉: https://forums.kleientertainment.com/topic/85655-server-no-longer-using-steam-collection/

**Comment by BraisGabin** [comment] 2017-12-27 15:22
And for this comment:

>  I do know that Steam has removed support for a workshop download method that some other games were using, it is possible this is effecting DST aswell. Is anyone currently able to download mods using the ServerModSetup method? 

I think that we must keep this open as a bug. Klei will probably change how to dowload mods so.

**Comment by thasmo** [comment] 2017-12-27 15:24
😢

**Comment by dbiagi** [comment] 2017-12-27 15:26
Not tried it yet, but, as a workaround, mapping a folder with mod files and configs to /opt/dst/mods/ should work, right?
Kinda like this:

```yml
world-2:
    image: dstacademy/dontstarvetogether:0.7
    tty: true
    stdin_open: true
    command: dst-server start --update=mods
    ports:
      - "11000:10999/udp"
    env_file:
      - "world-2.env"
    volumes:
        - "./world-2:/var/lib/dsta/cluster"
        - "./mods:/opt/dst/mods/"
```

**Comment by BraisGabin** [comment] 2017-12-27 15:28
Yeah, it should work.

**Comment by thasmo** [comment] 2017-12-27 15:28
That may work.

**Comment by BraisGabin** [comment] 2017-12-28 16:37
I tried to workaround this with `workshop_download_item 343050 382501575` but it didn't work. If someone know how to make that command work on steamcmp we can download the mods with that.

I did a bit more research here: https://forums.kleientertainment.com/topic/85655-server-no-longer-using-steam-collection/

**Comment by DylanYasen** [comment] 2017-12-29 16:24
can confirm manual mapping the mod folder works!
omg I was banging my head so hard yesterday as well. finally got the mods working.
thanks for the help!

**Comment by BraisGabin** [comment] 2017-12-29 23:48
The bug tracker is open again! Here is this bug reported: https://forums.kleientertainment.com/klei-bug-tracker/dont-starve-together/dedicated-server-mods-are-not-downloading-r8224/

**Comment by BraisGabin** [comment] 2017-12-30 14:25
Some news: https://forums.kleientertainment.com/topic/85655-server-no-longer-using-steam-collection/?tab=comments#comment-988480

```
steamcmd +@ShutdownOnFailedCommand 1 +login anonymous +force_install_dir /tmp +workshop_download_item 322330 382501575 +quit
```

Ok, baby steps. I was using a wrong appid. But now I'm having a different error, a timeout.

Linweiqing pointed out that it doesn't work with anonymous login, and he was right. I logged in with my account and it worked! Problem... How can we script this?

A default account? Say the users to use its own account? I don't know...

**Comment by thasmo** [comment] 2017-12-30 15:27
I believe Klei needs to have a look and actually comment on it whether it's their responsibility or Steam's.

**Comment by thasmo** [comment] 2018-01-03 16:07
Seems like it was Valve/Steam's fault and it has been fixed by now. Can someone confirm?

**Comment by BraisGabin** [comment] 2018-01-03 19:51
Yeap, they fixed it. I just checked.

**Closed as completed by BraisGabin** 2018-01-03 19:51 UTC
Labels: bug, question, research

**Comment by meteorlxy** [comment] 2018-01-16 07:55
So in the latest version (0.8.0 now), if I want to enable some mods, I must rebuild the whole image?

**Comment by BraisGabin** [comment] 2018-01-16 18:10
This question is no related with this issue. Please open a new issue and I'll answer it. (I want to answer it in a reachable way because it's a really good question and it's going to be asked more than once).
